// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/slack": {
            "get": {
                "description": "Redirects the user to Slack for authentication",
                "tags": [
                    "Auth"
                ],
                "summary": "Start Slack OAuth",
                "responses": {
                    "307": {
                        "description": "Temporary Redirect"
                    }
                }
            }
        },
        "/auth/slack/callback": {
            "get": {
                "description": "The endpoint Slack redirects to after user approval. Sets the session cookie.",
                "tags": [
                    "Auth"
                ],
                "summary": "Slack OAuth Callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth code from Slack",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "303": {
                        "description": "Redirect to frontend callback"
                    }
                }
            }
        },
        "/like/{hash}": {
            "post": {
                "description": "Adds a track to a user's liked tracks",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Likes"
                ],
                "summary": "Likes a track",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Track Hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes a track from the user's liked tracks",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Likes"
                ],
                "summary": "Removes a liked track",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Track Hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "description": "Returns the email and userID of the logged-in user via session cookie",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current session",
                "responses": {
                    "200": {
                        "description": "{\"email\": \"...\", \"userID\": \"...\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Not logged in",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/playlists": {
            "get": {
                "description": "returns the nested folder structure of playlists",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Playlists"
                ],
                "summary": "Get playlist tree",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Playlist"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new entry in the playlist tree",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Playlists"
                ],
                "summary": "Create a playlist or folder",
                "parameters": [
                    {
                        "description": "Playlist creation data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreatePlaylistRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Playlist"
                        }
                    }
                }
            }
        },
        "/playlists/{id}": {
            "get": {
                "description": "returns the contents of a playlist with a certain id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Playlists"
                ],
                "summary": "Get playlist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Playlist ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Playlist"
                        }
                    },
                    "404": {
                        "description": "Playlist not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes a playlist or folder. Use with caution.",
                "tags": [
                    "Playlists"
                ],
                "summary": "Delete a playlist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Playlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/playlists/{id}/tracks": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Playlists"
                ],
                "summary": "Add track to playlist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Playlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Track Hash",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.AddTrackRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/playlists/{id}/tracks/{hash}": {
            "delete": {
                "tags": [
                    "Playlists"
                ],
                "summary": "Remove track from playlist",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Playlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Track Hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Get user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ProfileData"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Search tracks with fuzzy matching, metadata filtering, and range queries.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Advanced Track Search",
                "parameters": [
                    {
                        "type": "string",
                        "name": "album",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "albumArtist",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "comments",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "composer",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "genre",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "label",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "lastHash",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "lastTimeStamp",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "maxBPM",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "maxBitRate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "maxDateAdded",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "maxDuration",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "maxPlayCount",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "maxRating",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "maxRelease",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "maxSampleRate",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "maxSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "maxTimeStamp",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "minBPM",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "minBitRate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "minDateAdded",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "minDuration",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "minPlayCount",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "minRating",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "minRelease",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "minSampleRate",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "minSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "minTimeStamp",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "mix",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "query",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "remixer",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "tonality",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "uploadedBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Track"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tracks": {
            "get": {
                "description": "Get a full list of all tracks in the database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tracks"
                ],
                "summary": "List all tracks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Track"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Upload a single music file and extract metadata",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Tracks"
                ],
                "summary": "Upload a track",
                "parameters": [
                    {
                        "type": "file",
                        "description": "The music file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Upload Successful: \u003chash\u003e",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tracks/batch": {
            "post": {
                "description": "Upload multiple music files at once. Returns a list of results for each file.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tracks"
                ],
                "summary": "Batch upload tracks",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Multiple music files",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "207": {
                        "description": "Multi-Status: Returns success/error for each file",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.BatchUploadResponse"
                            }
                        }
                    }
                }
            }
        },
        "/tracks/page": {
            "get": {
                "description": "Get tracks using cursor-based pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tracks"
                ],
                "summary": "Paginated tracks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RFC3339 date cursor",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Tie-breaker hash cursor",
                        "name": "hash",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Track"
                            }
                        }
                    }
                }
            }
        },
        "/tracks/{hash}/file": {
            "get": {
                "description": "Stream a music file from storage using its hash",
                "produces": [
                    "audio/mpeg"
                ],
                "tags": [
                    "Tracks"
                ],
                "summary": "Download a track",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The track hash",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/xml": {
            "post": {
                "description": "Upload a Rekordbox collection XML to sync metadata and playlists",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Tracks"
                ],
                "summary": "Import Rekordbox XML",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Rekordbox XML file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Imported X tracks",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CuePoint": {
            "type": "object",
            "properties": {
                "blue": {
                    "type": "integer"
                },
                "green": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "num": {
                    "type": "integer"
                },
                "red": {
                    "type": "integer"
                },
                "start": {
                    "type": "number"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "domain.Playlist": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Playlist"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "imported": {
                    "type": "boolean"
                },
                "isFolder": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parentID": {
                    "type": "string"
                },
                "playlistID": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Track"
                    }
                }
            }
        },
        "domain.ProfileData": {
            "type": "object",
            "properties": {
                "Playlist": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Playlist"
                    }
                },
                "email": {
                    "type": "string"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.TrackMetadata"
                    }
                },
                "tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Track"
                    }
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "domain.Tempo": {
            "type": "object",
            "properties": {
                "battito": {
                    "type": "integer"
                },
                "bpm": {
                    "type": "number"
                },
                "inizio": {
                    "type": "number"
                },
                "metro": {
                    "type": "string"
                }
            }
        },
        "domain.Track": {
            "type": "object",
            "properties": {
                "artist": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "timeStamp": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "domain.TrackMetadata": {
            "type": "object",
            "properties": {
                "averageBpm": {
                    "type": "number"
                },
                "beatgrid": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Tempo"
                    }
                },
                "bitRate": {
                    "type": "integer"
                },
                "comments": {
                    "type": "string"
                },
                "composer": {
                    "type": "string"
                },
                "cuePoints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.CuePoint"
                    }
                },
                "dateAdded": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "genre": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "mix": {
                    "type": "string"
                },
                "playCount": {
                    "type": "integer"
                },
                "rating": {
                    "type": "integer"
                },
                "remixer": {
                    "type": "string"
                },
                "sampleRate": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "timeStamp": {
                    "type": "string"
                },
                "tonality": {
                    "type": "string"
                },
                "trackHash": {
                    "type": "string"
                },
                "uploadedBy": {
                    "type": "string"
                }
            }
        },
        "handler.AddTrackRequest": {
            "type": "object",
            "properties": {
                "trackHash": {
                    "type": "string"
                }
            }
        },
        "handler.BatchUploadResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handler.CreatePlaylistRequest": {
            "type": "object",
            "properties": {
                "isFolder": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parentID": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Record Pool API",
	Description:      "This is a music record pool server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
